### ISSUE TITLE
Size constrained training may be not robust with more epoches?

### ISSUE THREAD

**Issue by JunMa11** [LIVIAETS/miccai_weakly_supervised_tutorial#1]
Dear @josedolz ,

Thanks for sharing the tutorial code.
The size constrained loss works well within 200 epoches.
![image](https://user-images.githubusercontent.com/19947331/67586167-9723e800-f783-11e9-80ec-0bc6a3c00076.png)

However, if I increase the number of epoch (e.g., 500), the training is degraded. Specifically, the `SizeDiff` increases by 10 times.

![image](https://user-images.githubusercontent.com/19947331/67586432-334def00-f784-11e9-95bb-66764cb06370.png)

What is wrong with the training?

Best regards,
Jun

**Comment by josedolz** [comment]
Hi @JunMa11 
Thanks for pointing out this issue. The thing is that during the tutorial we had some issues accessing to our servers (even with VPN) and we had to do some work-arounds on the code. I have uploaded now the exact code I used in my talk. I run it twice - logs attached. You can see how both converge (one is slower) but they may be running for many epochs that it does not converge.

Best,
Jose

Run 1
<img width="823" alt="Screen Shot 2019-10-25 at 1 39 23 PM" src="https://user-images.githubusercontent.com/5444841/67594354-26081480-f732-11e9-94f3-c8a73ca9b301.png">

<img width="823" alt="Screen Shot 2019-10-25 at 1 43 14 PM" src="https://user-images.githubusercontent.com/5444841/67594362-2b655f00-f732-11e9-8b51-9c5b503b09de.png">

Run 2
<img width="823" alt="Screen Shot 2019-10-25 at 1 54 40 PM" src="https://user-images.githubusercontent.com/5444841/67594388-39b37b00-f732-11e9-9cda-b73881615f12.png">

<img width="823" alt="Screen Shot 2019-10-25 at 1 59 26 PM" src="https://user-images.githubusercontent.com/5444841/67594397-3e782f00-f732-11e9-9625-04ac4a70c972.png">

<img width="823" alt="Screen Shot 2019-10-25 at 2 07 10 PM" src="https://user-images.githubusercontent.com/5444841/67594405-433ce300-f732-11e9-9a2b-a68f1a345867.png">

**Comment by JunMa11** [comment]
Hi @josedolz 
Thanks for your quick reply.

Some codes are missing.

https://github.com/LIVIAETS/miccai_weakly_supervised_tutorial/blob/de1a52ddfacfb35ee9934cd02b42b7d0d5c29744/7-WeaklySup_Segmentation.py#L3

`ModuleNotFoundError: No module named 'SegmentationUtils'
`

**Comment by HKervadec** [comment]
I will fix this and #2 in the next few days. Some results are different because the demo used Pytorch 0.4 (quite old), whereas the initially submitted one is for the last version of Pytorch. Some minor difference in the framework might have been introduced, explaining the different results ; I will have to hunt that.

Overall, some problems arise because we trimmed the problem _a lot_ to fit a CPU and run under 10 minutes on a laptop (tiny toy network, only 10 training samples). This does not happen in real-world scenarios and applications.

**Comment by HKervadec** [comment]
6aca8bc puts back the PyTorch version, and the old numpy defined backward version that was run during the presentation. I updated the Readme as well:

>## Old code
> For reference only, we provide the run that was actually run during the MICCAI tutorial, in the `old_version` folder. This code is compatible with PyTorch 0.4 only, and is actually on old research code that we used at the time.
> 
> At the time, we were doing the forward and backward functions manually in NumPy, which complexifies the implementation and verification a bit.
Due to majors update for PyTorch in between, and perhaps few minor differences with the current full PyTorch implementation, small difference in results may arise.
> 
> We do not intend to update or support that old version, but users are free to explore it.

Since this one is compatible with PyTorch 0.4 only, and is much less readable, the full PyTorch implementation supersedes it. Tiny difference exist, both due to the evolution of the framework, and minor details in the implementation. This does not affect the validity of the results (as this is the same implementation of the different papers on the topic that we have).
